services:
  - type: web
    name: zidalco-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SUPABASE_MOCK
        value: false
    healthCheckPath: /api/health
